### ISSUE TITLE
The pretrained weights cannnot be downloaded.

### ISSUE THREAD

**Issue by gyc9709** [ykotseruba/SALICONtf#2]
Dear, I am trying to run your model, but I found that the pre-trained weights "download_pretrained_weights.sh" cannot be downloaded as illustrated in the readme. Could you please solve this problem?

**Comment by ykotseruba** [comment]
Sorry for that, the link in the download script is fixed now.

**Comment by gyc9709** [comment]
Dear Yulia,
&nbsp; &nbsp;Thanks a lot for your reply. I can download it now. Best regards to your team.
Sincerely,
Yichen




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yulia"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月26日(星期四) 晚上11:29
收件人:&nbsp;"ykotseruba/SALICONtf"<SALICONtf@noreply.github.com&gt;;
抄送:&nbsp;"Dandeline"<463791605@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ykotseruba/SALICONtf] The pretrained weights cannnot be downloaded. (#2)




Sorry for that, the link in the download script is fixed now.

**Comment by gyc9709** [comment]
Dear Yulia,
&nbsp; &nbsp; &nbsp;Sorry for bothering you again. I want to ask you what version of tensorflow do you use? I didn't see this in the requirements.txt.
Regards,
Yichen




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yulia"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月26日(星期四) 晚上11:29
收件人:&nbsp;"ykotseruba/SALICONtf"<SALICONtf@noreply.github.com&gt;;
抄送:&nbsp;"Dandeline"<463791605@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ykotseruba/SALICONtf] The pretrained weights cannnot be downloaded. (#2)




Sorry for that, the link in the download script is fixed now.

**Comment by ykotseruba** [comment]
I used tensorflow_gpu==1.13.0rc1 and Keras 2.2.4 with Python 3.5 (see requirements.txt from (https://github.com/ykotseruba/pySTAR-FC/blob/master/requirements.txt). If you prefer more recent tensorflow you can match it with the compatible Keras version and it should work fine.

**Comment by andriyrizhiy** [comment]
model cannot be downloaded again
![image](https://user-images.githubusercontent.com/41432542/104456524-7971b700-55b1-11eb-8aaa-be846bd70753.png)

**Comment by ykotseruba** [comment]
Unfortunately, we have issues with the server, hopefully we can get it running again in the next few days.

**Comment by ykotseruba** [comment]
The server is up now, sorry for the inconvenience.
